server.port: 8080

spring:
  jpa:
    show-sql: true
    
  h2:
    console:
      enabled: true
  logging:
  level:
    root: INFO
    com.example.ayoteralab.main: DEBUG
  file:
    path: logs
      
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always
    data: classpath:sql/schema.sql, classpath:sql/data.sql
    
  kafka:    
    bootstrap-servers: localhost:9092
    sessiontimeout: 200000
    connectiontimeout: 15000
    template:
      filetrans-topic: filetrans-topic
    consumer:    
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer   
      enable-auto-commit: true
      max-poll-records: 10     
      filetrans-group-id: filetrans-group             
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer 
    
      
